name: Setup
description: "Setup repository"
runs:
  using: composite
  steps:
    - name: Setup JDK 1.8 for x86
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: x86
        cache: 'maven'